[package]
name = "er-bullet-time"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
eldenring = "0.14.0"
fromsoftware-shared = "0.14.0"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3", features = ["fmt", "env-filter"] }
tracing-appender = "0.2"
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"
windows-sys = { version = "0.61.2", features = ["Win32_Foundation", "Win32_UI_Input_KeyboardAndMouse", "Win32_UI_Input_XboxController", "Win32_System_LibraryLoader"] }